on:
  push:
    branches:
      - master 

jobs:
  build-and-deploy:
    runs-on: windows-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' 

      
      - name: Restore dependencies
        run: dotnet restore

      
      - name: Build
        run: dotnet build --configuration Release --no-restore

      
      - name: Publish
        run: dotnet publish -c Release -o ./publish --no-build


  
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'githubapp' 
          package: './publish'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
         
